### ISSUE TITLE
errors when running sh build.sh command

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/aapt2#12]
build.sh: 23: ./autogen.sh: not found
build.sh: 24: ./configure: not found
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
error: src/incremental_delivery/sysprop/IncrementalProperties.sysprop.cpp: already exists in working directory
error: src/incremental_delivery/sysprop/include/IncrementalProperties.sysprop.h: already exists in working directory  error: src/libpng/CMakeLists.txt: No such file or directoryerror: src/selinux/libsepol/src/private.h: No such file or directory
error: src/protobuf/cmake/CMakeLists.txt: No such file or directory
error: src/base/tools/aapt2/ResourceTable.cpp: No such file or directory
error: src/base/tools/aapt2/ResourceUtils.cpp: No such file or directory
error: src/base/tools/aapt2/Resources.proto: No such file or directory
error: src/base/tools/aapt2/ResourcesInternal.proto: No such file or directory
error: src/base/tools/aapt2/cmd/Link.cpp: No such file or directory
error: src/base/tools/aapt2/cmd/Link.h: No such file or directory
error: src/base/tools/aapt2/java/JavaClassGenerator.cpp: No such file or directory
error: src/base/tools/aapt2/link/PrivateAttributeMover.cpp: No such file or directory
error: src/base/tools/aapt2/util/Util.cpp: No such file or directory
error: src/base/libs/androidfw/ResourceTypes.cpp: No such file or directory
error: src/base/libs/androidfw/include/androidfw/StringPiece.h: No such file or directory
error: src/boringssl/CMakeLists.txt: No such file or directory
build.sh: 44: Syntax error: "(" unexpected

**Comment by oSumAtrIX** [comment]
You are missing these dependencies:

https://github.com/ReVanced/aapt2/blob/main/build.sh#L10-L16

Additionally you are likely on the wrong OS. Check the workflow file for the correct runner image
