### ISSUE TITLE
Not enough options

### ISSUE THREAD

**Issue by PeterNjeim** [ReVanced/aapt2#7]
It seems the only option available is `h`. That means I can't use it for patching YouTube as the script requires `dir`, `legacy`, and `o`. Is this a bug or am I using it incorrectly

**Comment by Aunali321** [comment]
use this action https://github.com/revanced/aapt2/actions/runs/2512050666.

**Comment by PeterNjeim** [comment]
The compilation worked, however I'm not sure how to get the installation to work in Termux. I ommitted the `d` flag as I'm not connected via adb, I can run adb commands directly in Termux. Is there a way to make the script install locally on the device?

**Comment by PeterNjeim** [comment]
Got it working by following this guide to adb into yourself: http://blog.kmckk.com/archives/4092970.html. This shouldn't be necessary if the script gets updated to support Termux, but for now this suffices.
