### ISSUE TITLE
Aapt for armeabi-v7a have some issues

### ISSUE THREAD

**Issue by decipher3114** [ReVanced/aapt2#8]
![image](https://user-images.githubusercontent.com/84389932/190617690-223e3aff-1c9f-4974-969d-0b9c2bb9f40f.png)

I request you to please have a look and fix this

**Comment by decipher3114** [comment]
![Screenshot_20220916-172700_Termux](https://user-images.githubusercontent.com/84389932/190634266-49edef9c-f541-48bb-9582-f41684669aab.jpg)
Some error in aapt2 for arm64 as well.
I downloaded the these from the latest build

**Comment by oSumAtrIX** [comment]
Closing, due to issue being outdated.
